### ISSUE TITLE
Performance issues - 30s time lag on opening pages

### ISSUE THREAD

**Issue by buzypi** [jaap-karssenberg/zim-desktop-wiki#519]
First of all, thanks for a wonderful utility. I have been using Zim wiki since 2012 and absolutely love this utility. I am into education and have influenced several students to use it during their studies. We also use it in our company to check in information about company processes.

I started noticing performance issues around 2016 when the number of pages would have crossed 6000. I upgraded my laptop around this time (i7/16 GB RAM/SSD storage) and made a few hacks by disabling the index and only updating when I do an "Update Index". This served another 2 years.

Now, after 6 years and 12000 pages of heavily cross linked content, I am finding Zim almost unusable. It takes over 30 seconds to load and every page click freezes Zim for 10s of seconds before allowing me to view/edit. I would have happily moved on to some other solution, but unfortunately (and fortunately for Zim) there is no solution that serves my needs. I really love Backlinks and the automatic update of Backlinks when pages are moved around. This feature along with several other minute but well chosen features has made Zim the winner for me.

I am not sure if users like me would be supported in future, so I am thinking about alternatives. I find the lack of a web/mobile app sometimes crippling but I am prepared to let go of them for lack of a better solution. Google Keep/Evernote/One Note are not good enough when it comes to navigation at scale.

Is there anyway we can think of improving the performance of indexing so that users like me can continue using Zim? Is there some setting that can be added to prevent frequent index scans/updates and use them from a cache?

Related issues:
https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/182

I have tried deleting and re-creating the index - doesn't help. I believe the issue to be with the SQL queries on index and index updates.

Thanks again!

Gautham

**Comment by Osndok** [comment]
There is definitely a scaling issue wrt a large number of pages/links! I find your report fascinating b/c you mentioned the page load time... I really started noticing it with the add/edit link dialog box (which I would classify as a page editing bottleneck), and have not really noticed an issue wrt the actual page load, per se.

If you are feeling adventurous, you can try my version of zim that has several optimization trade-offs:
* https://github.com/Osndok/zim-desktop-wiki

Since the speed-ups have been primarily focused around the link insertion (but have been noticed elsewhere), I would be **very** interested to know if it makes your page load time faster.

**Comment by buzypi** [comment]
@Osndok I tried out your fork and certain operations are definitely faster. But the page freeze after navigation is still there and there is no noticeable difference from the original. :(

**Comment by jaap-karssenberg** [comment]
Trying to reproduce your issue so I can understand where the freeze comes from. Using [this](https://gist.github.com/jaap-karssenberg/07c02edf3e1ec8fbe4b9b74dfcd36675) script with "100 1 3" to generate a notebook of 10000 pages with 0-3 random links per page.

Observations:

- Startup is almost instantaneous. 
- Navigation seems to give 1-2 sec timeouts, but not always
- Jump to ... autocompletion comes to a grinding halt

So I observe the issues @Osndok refers to, but not your timeout issue.
Not sure what would need to be added to the scrpit make it occur.

Testing on a reasonable old laptop with normal HD under linux. Zim version 0.68.

**Comment by Osndok** [comment]
@buzypi are you running from an SSD? I ask b/c dying hard disks have been known to get slower-and-slower as the number of retries needed to read a sector increases.

**Comment by buzypi** [comment]
@Osndok This is a SSD. I can try on a different laptop, but then I have no performance issues with my other work, which utilizes decent amount of CPU/RAM/Storage.

@jaap-karssenberg I would like to help out in reproducing the issue. But since I don't know what's the best way to do that, I would like to give you the larger context and possible areas where I anticipate issues.

First things first, I use Zim as a Personal Information Management system to organize entities that I encounter on a daily basis. I am a voracious user of Zim as you might have realized by now!

An entity could be a Person, a Company, a Place, a Date etc. I have 25 such top level entities currently. Here is an example:

Suppose I want to refer to Jaap, I may have a page as :Person:Jaap. This page has information about Jaap, example, his email id, his phone number and other information. Suppose I have an interaction with a Person on a specific day, I may capture it as follows:

```
Call with :Person:Jaap or :Date:2018:08:23
Details follow
```

I have over 1400 companies and 1300 people.

I mostly don't capture any content in the journal pages itself. But I use them for Backlinks. I have renamed Journal pages as :Date.

I have the habit of capturing links with a reference to a Date page for every link I capture in Zim wiki. For example:

```
https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/519
[[:Date:2018:08:23]]
```

This helps me because I can go to any Date page and I now get to know the various entities I encountered that day in backlinks. I have :Date links from 2012 to 2018 for almost every single day, so we are talking of over 2000 non-existent pages with only backlinks.

Further, some of my pages could easily have over 100 links with 100 such date links below them. This happens when I run some import scripts to move my bookmarks from an external system like Google Keep into Zim. Normally, the script gives me a single page content. I would eventually move the content around to other pages.

Can the number of backlinks from a single page or non-existent pages with backlinks deteriorate performance?

I tried disabling ALL plugins to ensure that this is not caused by any of the plugins. No major change in performance.

Here are some stats from the index.db database if you want:

```
files: 12335
links: 20920
pages: 14768
tags: 102 (I don't use Tags - this should be mostly auto-generated)
tagsources: 117
tasklist: 143
```

Some other stats from the directory:

```
$ find . -name "*" | grep -v ".git" | wc -l
12395

$ find . -name "*.txt" | wc -l             
10697

$ for file in `find . -name "*.txt"`;do cat $file;done | wc -l
338434
```

I will be free to share any other information you need to investigate further.

Please note: I didn't talk about any kind of timeout. There is no failed operation. The page eventually loads, just that it takes a really long time to do so.

**Comment by buzypi** [comment]
And yeah, one more observation: When I navigate by clicking on a link or a page in the sidebar, I observe that sometimes the page loads and then the application freezes, while sometimes the application freezes and then the page loads.

I see almost zero disk usage and 100% CPU usage during this time.

This clearly seems to indicate some async operation that is blocking the main thread.

**Comment by jaap-karssenberg** [comment]
I will modify the script to generate lots of links to non-existing pages,
and fiddle around to match your statistics, see if that helps to reproduce.

Judging by the command line I assume you are also running under linux.

Just to be sure, can you confirm what version of zim you are using? If
other than 0.68 I'll check whether the version changes anything.

-- Jaap

**Comment by buzypi** [comment]
That's right - I am on an Ubuntu 16.04 Desktop.

I have tried with both 0.67 and 0.68 versions - the problem is there with both of these versions.

**Comment by nbeaver** [comment]
Possibly related: https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/311

**Comment by buzypi** [comment]
Here is one more observation. After running Zim wiki for a while and having navigated a few pages, the `self.cache` in `get_mytreeiter` seems to be fully populated and has all entries from pages. But there seem to be requests for some treepath's that don't seem to exist in the cache (and will never be).

I added the following log lines:

```
  def get_mytreeiter(self, treepath):
    if treepath in self.cache:
      logger.info('self.cache has {} entries'.format(len(self.cache)))
      return self.cache[treepath]

    logger.info('{} not found in cache'.format(treepath))
...
```
and here is what I see:

```
...
INFO: (29, 4, 5) not found in cache
INFO: self.cache has 14771 entries
INFO: self.cache has 14771 entries
INFO: self.cache has 14771 entries
INFO: (29, 5, 2) not found in cache
INFO: self.cache has 14771 entries
INFO: self.cache has 14771 entries
INFO: self.cache has 14771 entries
INFO: self.cache has 14771 entries
INFO: self.cache has 14771 entries
INFO: (29, 6, 0, 0, 0, 1) not found in cache
INFO: (29, 6, 0, 0, 1) not found in cache
INFO: (29, 6, 0, 1) not found in cache
INFO: (29, 6, 1) not found in cache
INFO: self.cache has 14771 entries
INFO: (29, 8) not found in cache
INFO: (30,) not found in cache
INFO: self.cache has 14771 entries
...

The number of entries in cache never crosses 14771.

**Comment by Osndok** [comment]
Yeah... something doesn't seem quite right here.

It **sorta** makes sense, but I don't fully understand what this function is doing... it seems like it might have some **broken** optimization or pagination cruft from a refactor from times past.

https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/master/zim/notebook/index/pages.py#L804
```
ORDER BY sortkey, name LIMIT 20 OFFSET ?
...
break # avoid overwriting cache because of ref count
```
If the sortkey (by itself) seems benign, but if it does not line up with how we scan the index (say for a localization issue), then the rest of the function will make us hit the database multiple times for every page.

"LIMIT 20" has a magic number in it... and makes me wonder if something bad happens when you get to the 21st element... why do we have a limit anyway? why not encache all of the page's siblings? It looks like pagination, but we are not incrementing the offset..

"OFFSET" indicates that we already knew the precise record we wanted, but if we were actually confident in this odd way of addressing a table row... since we use this iterator for indexing... which can create gray placeholders... does that mean this offset will become invalid?

the ```break``` is the worst part... b/c AFAICS we haven't really even made sure that we found the page we are looking for... so **the moment we find any cousin in the cache**, we  stop? Even if (by some bizarre case) we have not reached our offset? This totally does not seem right...

If I were to blindly start debugging this out of ignorance, I think I would try something like:
```
diff --git a/zim/notebook/index/pages.py b/zim/notebook/index/pages.py
index 9f5a340e..cd299c13 100644
--- a/zim/notebook/index/pages.py
+++ b/zim/notebook/index/pages.py
@@ -818,17 +818,16 @@ class PagesTreeModelMixin(TreeModelMixinBase):
 		offset = treepath[-1]
 		for i, row in enumerate(self.db.execute('''
 			SELECT * FROM pages WHERE parent=?
-			ORDER BY sortkey, name LIMIT 20 OFFSET ?
+			ORDER BY sortkey, name
 			''',
-			(parent_id, offset)
+			(parent_id)
 		)):
 			mytreepath = parentpath + (offset + i,)
 			if mytreepath not in self.cache:
 				n_backlinks = self.db.execute("SELECT COUNT(*) FROM links WHERE target=?",(row['id'],)).fetchone()[0];
 				self.cache[mytreepath] = MyTreeIter(mytreepath, row, row['n_children'], IS_PAGE, n_backlinks)
-			else:
-				break # avoid overwriting cache because of ref count
 
+		assert treepath in self.cache
 		return self.cache.get(treepath, None)
 
 	def find(self, path):
```

...shot in the dark...fwiw.

**Comment by mlncn** [comment]
I'm in the situation that others posting on this thread, except i jumped into it trying to [escape performance issues in Tomboy](https://github.com/tomboy-notes/tomboy/issues/54)— [importing](https://bugs.launchpad.net/zim/+bug/208995/comments/1) my 10,000+ notes...  only to find the same performance issues.  (Note: the delays i reported in the Tomboy issue queue are worse than here because they are before moving to a new computer with 32GB RAM and Intel Core i7-8750H CPU @ 2.20GHz × 12... so yeah, i should be able to handle a few hundred thousand text notes more or less instantly, you'd think?)

Zim Wiki getting the same performance as an outdated version of Tomboy is actually better than more current GNote and Tomboy-NG, and i am so so excited that there's active work on improving performance!

I'm on Zim 0.68-rc1 (the version in the Ubuntu Bionic repos is a little behind).

* Search is slow (5-10 seconds), and doesn't find everything, even after choosing "Update index" and waiting the five minutes for that to complete.
* Creating a note hangs on typing the name after the first character or two, hangs on opening the new note, and hangs again after the note is opened
* Renaming a note, even a new one with no backlinks, hangs for quite a while.

**Comment by buzypi** [comment]
I believe most of the old desktop software is yet to make use of the multi-core capabilities of current systems, so we are still talking about only one of the 4/8 cores being used for computation. The RAM usage is in 100s of MBs which is a fraction of what you have, so even that doesn't help.

**Comment by buzypi** [comment]
@Osndok While this may seem like a simple solution, the moment you use any system command, you are risking compatibility. Zim wiki has been designed to work in all OSs and these things would break it.

**Comment by Osndok** [comment]
I wonder about this comment:
```
sort by id to ensure parents are found before children
```

Does this assumption break if I:
* create page A (id 1?)
* create page B (id 2?)
* drag A under B, to make B(2) have a child A(1)

**Comment by jaap-karssenberg** [comment]
Haven't yet been able to reproduce the "lag on page load" issue, will try out more.

In the mean time commit 17f8515441bafbbb700383232f5823536393e1ab should fix performance of the completion of the "jump to" dialog and others.

**Comment by jaap-karssenberg** [comment]
Let's focus the discussion on this issue on the time lag on opening pages. For different performance aspects with large notebooks please open separate tickets.  See e.g. issue #64 for search speed

**Comment by jaap-karssenberg** [comment]
No able to reproduce the issue with [this script](https://gist.github.com/jaap-karssenberg/07c02edf3e1ec8fbe4b9b74dfcd36675) to generate a notebook. It produces 3 levels of 25 pages, resulting in > 15_000 in total. Also made each page generate random "date" links over a span of 8 years, so up to 8 * 12 * 30 = ~ 2880 non-existing pages being links *a lot*

Interesting observations

- Without links loading a page is slow ~10 sec but with links it comes to grinding halt and the window is never shown in the first place
- Without links the indexing takes ~ 3 minutes but with links it takes > 1 hour ! And especially hangs for a long time after last file is indexed.
- Tested also with "next" branch because it allows disabling the index side pane (it's a plugin now) -- interestingly in the "next branch" the notebook without links works snappy - regardless of the side pane is loaded or not -- so Gtk3 and/or python3 is more efficient here than Gtk2/python2 !
- Unfortunately also "next" branch can't handle the amount of links

So I'll be focussing on the way the indexer handles links - there is also something going on with the pageindex widget, but this goes away in python3/Gtk3 branch.

**Comment by buzypi** [comment]
Great! I am glad that you were able to reproduce the issue. You can post patches here and I can share stats on actual runs.

Thanks!

**Comment by jaap-karssenberg** [comment]
Checked in a patch that should speed up indexing of large notebooks. Indexing the test notebook initially took over an hour and now runs in less than 5 minutes. Feel there is still room for improvement, but wanted to put this out there for testing.

Please test with the python3 branch at commit 1c26175730f5346c9140dd88eed206367daebd1b and let me know whether it improves usability for you.

- indexing speed should be improved
- changing one page to the next should not slow down depending on notebook size

**Comment by buzypi** [comment]
Thanks for this. This definitely has solved the performance problem and things are suddenly fast!

However, here are a couple of severe bugs (presumably blockers) I encountered:

1. Mouse click does not seem to work in the page anymore to move the cursor around. This also means I can't click on a link to jump to a page. However, I can move the cursor around using the keyboard and edit the page.

When run in debug mode, I keep seeing this error in the terminal as I move my mouse:

```
Traceback (most recent call last):
  File "zim-desktop-wiki-1c26175730f5346c9140dd88eed206367daebd1b/zim/gui/pageview.py", line 3562, in on_motion_notify_event
    self.update_cursor(coords)
  File "zim-desktop-wiki-1c26175730f5346c9140dd88eed206367daebd1b/zim/gui/pageview.py", line 4004, in update_cursor
    ok, iter = self.get_iter_at_location(*coords)
TypeError: 'TextIter' object is not iterable
```

2. Link to page dialog does not show any suggestions now (including if I start with colon).

I get this trace when I open the Insert Link dialog for the first time:

```
Traceback (most recent call last):
  File "zim-desktop-wiki-1c26175730f5346c9140dd88eed206367daebd1b/zim/plugins/pathbar.py", line 456, in do_focus
    if direction in (Gtk.DIR_TAB_FORWARD, Gtk.DIR_TAB_BACKWARD) \
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'DIR_TAB_FORWARD'
```

Python3 version:

```
python3 --version
Python 3.5.2
```

GTK versions:

```
dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                     Version                   Architecture              Description
+++-========================================-=========================-=========================-======================================================================================
ii  libgtk-3-0:amd64                         3.18.9-1ubuntu3.3         amd64                     GTK+ graphical user interface library
ii  libgtk2.0-0:amd64                        2.24.30-1ubuntu1.16.04.2  amd64                     GTK+ graphical user interface library
```

A couple of minor bugs (which can be opened separately if needed):
1. When I want to Jump to a page (Ctrl+J) there is a debounce issue if I type very fast (I type at over 80wpm). I don't see any suggestions after I type a keyword. However, this issue is not there if I type the characters slowly. Not sure if this issue came up due to the bug fix, but this was not there in the 0.68 version.
2. The bookmarks bar does not occupy the available width and shows Left and Right arrows even though there is ample space

**Comment by jaap-karssenberg** [comment]
Hi Gautham,

Both issues do not occur on my system. The first one hints at incompatible
API, but can't imagine that it is unstable between the exact version you
have installed and the one I have.

You can try removing the "ok, " at the start of line 4004 and see if it
works.

Btw. please open new reports for these issues so we can track them
independently. This issue is strictly about the performance which seems is
mostly solved now.

Thanks,

Jaap

**Comment by buzypi** [comment]
@jaap-karssenberg I just wanted you to confirm that the bugs are not because of the performance improvements. If you are sure of that, we can close this issue and I will be happy to open new issues for these bugs.

It may well be because of the Python3/GTK3 combination, which I have never tried. I am on Ubuntu 16.04. I will try it on an Ubuntu 18.04 just to be sure.

**Comment by buzypi** [comment]
Removing ok fixed issue 1. I had to remove it in 2 places in the same file. The insert link issue still is there.

**Comment by buzypi** [comment]
@jaap-karssenberg I believe that there are still some bugs to be fixed with GTK3 before launching a stable version as per: https://github.com/jaap-karssenberg/zim-desktop-wiki/milestone/5. Would it be possible to provide a Python2/GTK2 port for this performance issue? If that's a big ask, I think we can wait for GTK3 to stabilize.

**Comment by jaap-karssenberg** [comment]
The indexing improvement can be ported back. But the lag due to the index
pane is gone in gtk3. I suspect that can not be fixed in Gtk.

**Comment by jaap-karssenberg** [comment]
Ported back the fix to "master" branch - see commit 6c427207cef494a81516a021ddb363b1c1ad9563

To my surprise it also seems to fix the lag while opening pages after indexing is up to date. Please give it a try.

**Comment by jaap-karssenberg** [comment]
Closing this issue. Please open new issues for further performance hits if any.

Regards,

Jaap
